[package]
name = "bevy_polyline2d"
version = "0.1.0"
edition = "2021"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 2

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
bevy_pancam = "0.14.0"
